In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.__config__)

1.20.3
<module 'numpy.__config__' from 'C:\\Users\\admin\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [4]:
x = np.zeros(10, int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array 

In [6]:
n = np.zeros((4,4))
print(n)
print("%d bytes" % (n.size * n.itemsize))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
128 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [10]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [11]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)

In [12]:
x = np.arange(10,50)
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
x = np.arange(0,9)
print(np.reshape(x,(3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find the indices of non-zero elements from [1,2,0,0,4,0]

In [16]:
a = np.array([1,2,0,0,4,0])

print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [17]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [18]:
x = np.random.random((3,3,3))
print(x)

[[[0.85176357 0.94020684 0.4682827 ]
  [0.63048738 0.00252796 0.88203705]
  [0.8109513  0.95438691 0.28765972]]

 [[0.58895591 0.47761161 0.43258795]
  [0.11495469 0.18896791 0.06274194]
  [0.08168172 0.423204   0.78588759]]

 [[0.98797694 0.70753804 0.9512125 ]
  [0.66628081 0.88023372 0.3730704 ]
  [0.10143877 0.04580799 0.22247053]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.38421432 0.71838646 0.60593486 0.48022415 0.45819081 0.72347373
  0.82481092 0.59560283 0.88216601 0.11779481]
 [0.30956828 0.50930902 0.208358   0.6753652  0.36927857 0.91603045
  0.07828336 0.49467666 0.21612591 0.32332862]
 [0.26165974 0.11449679 0.12431004 0.25623182 0.70361282 0.56151817
  0.69410117 0.23209659 0.10039542 0.47171139]
 [0.26729391 0.43886676 0.35546696 0.20481265 0.93461932 0.61379816
  0.66742143 0.37676022 0.22989465 0.64030918]
 [0.53883507 0.17594517 0.30704961 0.92097729 0.68145732 0.25421592
  0.55487944 0.34282318 0.88614526 0.98520465]
 [0.79041027 0.9102839  0.47344192 0.71431125 0.28709884 0.37117399
  0.02704253 0.536137   0.22117643 0.20038527]
 [0.14652573 0.18361433 0.22673582 0.90174896 0.05480207 0.33408089
  0.87134306 0.59615116 0.96778009 0.75541226]
 [0.03315945 0.1368343  0.40140305 0.48738581 0.23974413 0.62374492
  0.2120454  0.49268836 0.4786168  0.53134312]
 [0.88581727 0.89589262 0.78437849 0.30406461 0.27271665 0.86709284
  0.3325832 

#### 14. Create a random vector of size 30 and find the mean value 

In [26]:
x = np.random.random(30)
x.sort()
print(x)

[0.02750183 0.0675039  0.06886183 0.09511471 0.11362903 0.16157738
 0.26142152 0.27411329 0.31172305 0.32048316 0.34879892 0.35108672
 0.3749914  0.51998611 0.54613075 0.56497869 0.57076382 0.57808978
 0.60323526 0.61126107 0.68877707 0.69876386 0.70888465 0.75265393
 0.75378925 0.77518094 0.92569906 0.96688628 0.99564604 0.99737071]


#### 15. Create a 2d array with 1 on the border and 0 inside

In [27]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [28]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

In [29]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [31]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [35]:
#x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [37]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [38]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.83725016 0.77083093 0.97752887 0.63980105 0.47180442]
 [0.33167691 0.14546968 1.         0.54034588 0.20705149]
 [0.83030532 0.84479936 0.09801057 0.52891257 0.43115133]
 [0.045729   0.80716831 0.32644294 0.         0.3719706 ]
 [0.81924946 0.30039293 0.81948261 0.93680061 0.4682461 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [39]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [44]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))

np.dot(arr_1,arr_2)

array([[0.27872962, 0.43777277],
       [0.30734661, 0.85997337],
       [0.36267399, 0.89284514],
       [0.55113742, 1.01352416],
       [0.34887304, 0.83814696]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

#### 26. What is the output of the following script? (★☆☆)
```
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```
```

In [47]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [49]:
Z = np.arange(5)
Z ** Z

array([  1,   1,   4,  27, 256], dtype=int32)

In [50]:
Z = np.arange(5)
2 << Z >> 2 # false

array([0, 1, 2, 4, 8], dtype=int32)

In [51]:
Z = np.arange(5)
Z <- Z # legal

array([False, False, False, False, False])

In [52]:
Z = np.arange(5)
1j*Z # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [53]:
Z = np.arange(5)
Z/1/1 # legal

array([0., 1., 2., 3., 4.])

In [54]:
Z = np.arange(5)
Z<Z>Z # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [56]:
np.array(0) / np.array(0)

C:\Users\admin\AppData\Local\Temp/ipykernel_1948/873513115.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [57]:
np.array(0) // np.array(0)

C:\Users\admin\AppData\Local\Temp/ipykernel_1948/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [58]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ?

In [59]:
arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr) 

[[0.68674585 0.90978644 0.37915956 0.48024243 0.06036136]
 [0.00915093 0.33344506 0.96397703 0.533736   0.58363855]
 [0.59159922 0.33474364 0.997332   0.72119047 0.21089004]
 [0.42101267 0.7285251  0.76394277 0.22754002 0.59304075]
 [0.97224354 0.06101976 0.14608661 0.62148293 0.67155713]]
[[0.69 0.91 0.38 0.48 0.06]
 [0.01 0.33 0.96 0.53 0.58]
 [0.59 0.33 1.   0.72 0.21]
 [0.42 0.73 0.76 0.23 0.59]
 [0.97 0.06 0.15 0.62 0.67]]


#### 30. How to find common values between two arrays? (★☆☆)

In [62]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[1 2 6 7]


#### 31. How to ignore all numpy warnings (not recommended)?

In [63]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [64]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\admin\AppData\Local\Temp/ipykernel_1948/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [67]:
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print ("Yesterday is "+ str(yesterday))
print ("Today is "+ str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2022-08-31
Today is 2022-09-01
Tomorrow is 2022-09-02


#### 34. How to get all the dates corresponding to the month of July 2016?

In [66]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [69]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [72]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[7. 9. 2. 9. 2. 2. 7. 4. 2. 4.]
[7. 9. 2. 9. 2. 2. 7. 4. 2. 4.]
[7. 9. 2. 9. 2. 2. 7. 4. 2. 4.]
[7 9 2 9 2 2 7 4 2 4]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [73]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [74]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [75]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [76]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.16454019 0.20299254 0.25300174 0.4025152  0.55146917 0.56569977
 0.60892537 0.71344875 0.80911106 0.99729852]


#### 41. How to sum a small array faster than np.sum?

In [77]:
import functools as ft
Z = np.arange(10)
#np.add.reduce(Z)
ft.reduce(np.add,Z,0)

45

#### 42. Consider two random array A and B, check if they are equal

In [78]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print('*'*60)
print(B)
print('*'*60)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 0 1 0]
************************************************************
[0 0 0 1 0]
************************************************************
False
False


#### 43. Make an array immutable (read-only)

In [79]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [80]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.15176049 1.11417724 0.81259327 1.34839606 1.14595435 1.25790226
 0.75030754 0.88037994 1.09004895 0.48423686]
[0.87335504 0.62167526 0.73354012 0.81249928 0.9765645  0.74752803
 0.48263484 1.29859977 0.60437941 0.10482957]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [81]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[0.45710158 0.34950347 0.61804372 0.67622806 0.61998911 0.48288256
 0.36825958 0.22786607 0.19156449 0.66039081]
[0.45710158 0.34950347 0.61804372 0.         0.61998911 0.48288256
 0.36825958 0.22786607 0.19156449 0.66039081]


#### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [82]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays X and Y, construct a Cauchy matrix C (Cij =1/(xi-yj))

In [83]:
X = np.arange(8)
Y = X + 0.5
C = 1.0/np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [84]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array?

In [87]:
np.set_printoptions(threshold=256)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [88]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[5.48497437 0.566993   2.88276893 8.88819357 5.88772665 1.22639443
 1.55576955 9.1977356  7.64532511 1.21115399]
************************************************************
5.484974366011977


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [89]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [90]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.83736024 0.5982125  0.71446815 0.58061867 0.88176667
  0.19016983 0.46273231 0.4508727  0.44124735]
 [0.83736024 0.         0.79600524 0.38597041 0.49291435 0.04947407
  0.66103155 0.65530536 0.59919527 0.56086117]
 [0.5982125  0.79600524 0.         0.94956002 0.30309966 0.84367773
  0.48418474 0.18467768 0.24071922 0.28481868]
 [0.71446815 0.38597041 0.94956002 0.         0.6813904  0.39321812
  0.60043828 0.77016974 0.71078782 0.66602041]
 [0.58061867 0.49291435 0.30309966 0.6813904  0.         0.54069391
  0.40087265 0.18666378 0.15086974 0.14187464]
 [0.88176667 0.04947407 0.84367773 0.39321812 0.54069391 0.
  0.7073224  0.70448564 0.64853091 0.61030281]
 [0.19016983 0.66103155 0.48418474 0.60043828 0.40087265 0.7073224
  0.         0.31724332 0.28845663 0.26816361]
 [0.46273231 0.65530536 0.18467768 0.77016974 0.18666378 0.70448564
  0.31724332 0.         0.06029348 0.10489261]
 [0.4508727  0.59919527 0.24071922 0.71078782 0.15086974 0.64853091
  0.28845663 0.060293

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [95]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [96]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array

In [97]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2/(2.0 * sigma**2)))
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array?

In [98]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix

In [99]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
#print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column?

In [100]:
Z = np.random.randint(0,10,(5,5))
print(Z)


# Z_1 = Z
# for ind in range(5):
#     Z_1[:,ind].sort()
#print(Z_1)


print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[6 8 4 7 2]
 [5 8 8 3 3]
 [4 7 6 4 0]
 [1 4 4 0 1]
 [7 6 8 9 1]]
[[6 8 4 7 2]
 [5 8 8 3 3]
 [4 7 6 4 0]
 [7 6 8 9 1]
 [1 4 4 0 1]]
[[7 2 6 8 4]
 [3 3 5 8 8]
 [4 0 4 7 6]
 [0 1 1 4 4]
 [9 1 7 6 8]]


#### 60. How to tell if a given 2D array has null columns?

In [101]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[ True False False  True False  True  True False False False]
 [ True False  True False  True  True  True False  True False]
 [ True False  True  True  True  True False  True  True  True]]
[[False  True  True False  True False False  True  True  True]
 [False  True False  True False False False  True False  True]
 [False  True False False False False  True False False False]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array

In [102]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print (m)

0.48642018414088517


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [103]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute

In [104]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj,'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector(be careful with repeated indices)?

In [105]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 6. 2. 1. 3. 2. 5. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [106]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [107]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [108]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[37 54 52 68]
 [57 53 48 55]
 [44 34 50 57]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [109]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54294555 0.43916325 0.51390975 0.44798677 0.59356213 0.46744952
 0.65865941 0.54174789 0.44353253 0.39118334]


#### 69. How to get the diagonal of a dot product?

In [110]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

np.diag(np.dot(A, B))

array([111,  54,  34])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [111]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of given dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [112]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array?

In [113]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [114]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 84) ( 1, 94) ( 2, 47) ( 2, 85) ( 7, 22) ( 7, 70) ( 9, 26) ( 9, 71)
 (13, 63) (13, 94) (22, 25) (22, 54) (22, 70) (25, 54) (26, 71) (47, 85)
 (51, 69) (51, 94) (59, 62) (59, 65) (60, 88) (60, 90) (62, 65) (63, 94)
 (64, 65) (64, 91) (65, 91) (69, 94) (84, 94) (88, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [115]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array?

In [116]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [117]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [118]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[1 1 0 0 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0
 1 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 0 1 0 1 1 0 0
 0 1 0 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 1 1]
Negating a boolean: 
[0 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 1
 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 1
 1 0 1 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1 0 0 1 1 0 0]
original: 
[-0.50698574 -0.62600363  0.91437254  0.1291167  -0.83569697 -0.52503628
 -0.48000291  0.19287132 -0.46611358 -0.27327911]
Change the sign of float inplace: 
[ 0.50698574  0.62600363 -0.91437254 -0.1291167   0.83569697  0.52503628
  0.48000291 -0.19287132  0.46611358  0.27327911]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [119]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.91626303 10.67109672 10.59008487  2.22704991 14.10166733  2.12031095
  3.22518732  6.06149268  5.45452114  3.05129907]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [120]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.7764201   1.2147953   4.6647285   1.72283361  2.75663235]
 [11.90609525  1.88396951 10.47539733  0.73773364 13.16308852]
 [ 7.4136488   2.84951692  9.17404522  2.20569205  7.18994656]
 [ 1.12758876  9.05550311  0.93954487  9.99902743  3.36946035]
 [ 5.48371215  3.04873044  8.48012697  2.60443252  4.69770096]]


#### 82. Compute a matrix rank

In [121]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S> 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array?

In [122]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [124]:
Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 4]
   [2 2 1]
   [4 2 0]]

  [[4 4 2]
   [2 1 2]
   [2 0 0]]

  [[4 2 3]
   [1 2 2]
   [0 0 0]]

  [[2 3 3]
   [2 2 2]
   [0 0 2]]]


 [[[2 2 1]
   [4 2 0]
   [0 1 3]]

  [[2 1 2]
   [2 0 0]
   [1 3 4]]

  [[1 2 2]
   [0 0 0]
   [3 4 2]]

  [[2 2 2]
   [0 0 2]
   [4 2 4]]]


 [[[4 2 0]
   [0 1 3]
   [4 3 0]]

  [[2 0 0]
   [1 3 4]
   [3 0 3]]

  [[0 0 0]
   [3 4 2]
   [0 3 4]]

  [[0 0 2]
   [4 2 4]
   [3 4 0]]]


 [[[0 1 3]
   [4 3 0]
   [0 2 3]]

  [[1 3 4]
   [3 0 3]
   [2 3 3]]

  [[3 4 2]
   [0 3 4]
   [3 3 2]]

  [[4 2 4]
   [3 4 0]
   [3 2 1]]]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [125]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. For a 16x16 array, how to get the sum of a block-sum (the size of the block is 4x4)? 

In [126]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 89. How to get the n largest values of an array

In [127]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 91. How to create a record array from a regular array?

In [130]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats ='S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [133]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [134]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 1 1]
 [3 0 1]
 [4 3 4]
 [0 3 2]
 [3 2 0]
 [2 0 4]
 [3 3 3]
 [2 3 4]
 [4 2 2]
 [1 2 0]]
[[4 1 1]
 [3 0 1]
 [4 3 4]
 [0 3 2]
 [3 2 0]
 [2 0 4]
 [2 3 4]
 [4 2 2]
 [1 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation

In [135]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])



I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows?

In [136]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [137]:
A= np.arange(3)
B =  np.arange(12).reshape(3,4)
print (A)

[0 1 2]
